export enum QUERY_KEYS {
  AUTH = "auth",
  CITY = "city",
  ORDER = "order",
  STATE = "state",
  SELLER = "seller",
  COUNTRY = "country",
  PRODUCT = "product",
  QUESTION = "question",
  CATEGORY = "category",
  CONDITION = "condition",
  TRANSACTION = "transaction",
  NOTIFICATION = "notification",
  CONVERSATION = "conversation",
  FULL_TEXT_SEARCH = "full-text-search",
  USER_OFFER_N_BIDS = "user-offer-n-bids",
  SELLER_OFFER_N_BIDS = "seller-offer-n-bids",

  UNAUTHORIZED = "unauthorized",
  UNKNOWN_ERROR = "unknown-error",
}
